// End-to-end address derivation test:
//   mnemonic → seed → BIP-32 master → m/86'/0'/0'/0/0 → BIP-86 tweak → prl1p…
//
// This is the most important invariant for the wallet: if derivation
// regresses, restored wallets show the wrong address and funds appear
// "missing". We pin against the BIP-86 spec vector (which uses a
// known seed and a known final address) and additionally — when the
// PEARL_TEST_MNEMONIC / PEARL_TEST_ADDRESS env pair is set — against
// G's wallet from the vault, so the prod wallet's real address must
// derive bit-exact from its mnemonic.

import { describe, it, expect } from "vitest";
import { HDKey } from "@scure/bip32";
import * as bip39 from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english";
import {
  pearlAddressFromInternalKey,
  pearlAddressFromCompressedPubkey,
} from "../src/chains/pearl/address";
import { pearlParams } from "../src/chains/pearl/network";
import { DEFAULT_PEARL_PATH, masterFromSeed } from "../src/crypto/hd";

const params = pearlParams("mainnet");

// BIP-86 test vector 1 — canonical reference.
//   mnemonic: "abandon abandon abandon abandon abandon abandon abandon
//              abandon abandon abandon abandon about"
//   account 0, external chain, address index 0 (m/86'/0'/0'/0/0)
//   → output key a6086…dc684c (verified in address.test.ts)
const BIP86_MNEMONIC =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

const BIP86_INTERNAL_XONLY =
  "cc8a4bc64d897bddc5fbc2f670f7a8ba0b386779106cf1223c6fc5d7cd6fc115";

describe("End-to-end BIP-86 derivation", () => {
  it("BIP-39 mnemonic → seed → m/86'/0'/0'/0/0 → expected internal x-only key", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = HDKey.fromMasterSeed(seed);
    const child = master.derive(DEFAULT_PEARL_PATH);
    expect(child.publicKey).toBeTruthy();
    // child.publicKey is 33-byte compressed. Strip parity prefix → 32-byte x-only.
    const xOnly = child.publicKey!.slice(1);
    expect(Buffer.from(xOnly).toString("hex")).toBe(BIP86_INTERNAL_XONLY);
  });

  it("BIP-86 mnemonic → prl1p address (HRP-swapped from BTC vector)", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = masterFromSeed(seed);
    const child = master.derive(DEFAULT_PEARL_PATH);
    const xOnly = child.publicKey!.slice(1);
    const addr = pearlAddressFromInternalKey(xOnly, params);
    // BIP-86 BTC vector 1 produces output key a60869f…dc684c which encodes
    // to a fixed prl1p… address when re-encoded under our HRP.
    // BIP-86 BTC vector 1 = bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr.
    // Same 32-byte output key, re-encoded under "prl" HRP, has the same body
    // and a fresh bech32m checksum.
    expect(addr).toBe(
      "prl1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqw2cjwh",
    );
  });

  it("compressed-pubkey path matches internal-key path", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = masterFromSeed(seed);
    const child = master.derive(DEFAULT_PEARL_PATH);
    const compressed = child.publicKey!;
    const xOnly = compressed.slice(1);
    expect(pearlAddressFromCompressedPubkey(compressed, params))
      .toBe(pearlAddressFromInternalKey(xOnly, params));
  });

  it("invalid mnemonic is rejected by bip39", () => {
    expect(bip39.validateMnemonic("not a real mnemonic phrase here please", wordlist)).toBe(false);
  });
});

// Round-trip: a fresh mnemonic generated by us, derived twice, produces
// the same address. Catches any nondeterminism in our derivation
// pipeline (which would silently break restore flow).
describe("Wallet self round-trip", () => {
  it("the same mnemonic always derives the same prl1p address", async () => {
    // 12-word BIP-39 mnemonic, fully valid, generated offline.
    const mn = "legal winner thank year wave sausage worth useful legal winner thank yellow";
    const seed1 = await bip39.mnemonicToSeed(mn);
    const seed2 = await bip39.mnemonicToSeed(mn);
    expect(Buffer.from(seed1).toString("hex")).toBe(Buffer.from(seed2).toString("hex"));
    const m1 = masterFromSeed(seed1);
    const m2 = masterFromSeed(seed2);
    const a1 = pearlAddressFromInternalKey(m1.derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    const a2 = pearlAddressFromInternalKey(m2.derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    expect(a1).toBe(a2);
    expect(a1.startsWith("prl1p")).toBe(true);
  });

  it("two different mnemonics produce two different addresses", async () => {
    const a = await bip39.mnemonicToSeed("legal winner thank year wave sausage worth useful legal winner thank yellow");
    const b = await bip39.mnemonicToSeed("abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about");
    const addrA = pearlAddressFromInternalKey(masterFromSeed(a).derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    const addrB = pearlAddressFromInternalKey(masterFromSeed(b).derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    expect(addrA).not.toBe(addrB);
  });
});

// NOTE: btcd-oyster compatibility — the `oyster` btcd wallet tool uses
// a non-BIP-32 mapping from BIP-39 mnemonic → keys. Wallets created
// by oyster cannot be restored to PearlWallet via mnemonic alone (the
// derived address will differ). Direct private-key import is not yet
// supported; oyster users should stay on oyster until v0.2.
